### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by eapache** [evernote/android-state#10]
Hi there, we're interested in using this library, but we have a question about the license. As this library uses code-generating annotations, we're concerned that the output from the preprocessor might contain parts of the EPL source code in it thereby making the generated source a derivative work of the preprocessor. Can you confirm if this is the case and if so is it your intention that the output of the preprocessor not be subject to any licensing terms?

**Comment by vRallev** [comment]
I'm not a lawyer, so this is hard to answer for me. I'd say yes, the generated code is licensed under EPL, because it's generated with snippets which are licensed under EPL.

Why is this a problem for you? The generated code will only work if the library can be found at runtime, which is also licensed under EPL.

**Comment by eapache** [comment]
> I'm not a lawyer

I'm not either, just trying to cover my bases. Everything here is based on my understanding of the EPL.

> the generated code is licensed under EPL, because it's generated with snippets which are licensed under EPL.

That's unfortunate.

> Why is this a problem for you? The generated code will only work if the library can be found at runtime, which is also licensed under EPL.

The terms of the EPL (as I understand it) effectively require you to make source available with the binary. This isn't a problem for the library itself, since `android-state` is already publicly available here, and the EPL isn't viral (just including it in a project does not require the remainder of the project to be EPL-licensed).

However, if the generated code is also EPL-licensed then we are required (again, per my non-lawyer understanding) to make all the generated source publicly available, which includes references to internal class names, instance variable names, etc. which we would prefer to remain private.

**Comment by eapache** [comment]
To be a bit more concrete, if we had the following class using android-state:
```
class SecretSauceFoo {
    @State int secretIntThing;
}
```

Then (per my understanding, *if* the generated code is also under the EPL) we are required to publish the source for `class SecretSauceFoo$$StateSaver`, which we do not want to do since it would expose the existence and naming of `SecretSauceFoo` and `secretIntThing`.

**Comment by vRallev** [comment]
I see it a little different. EPL requires you to publish changes you made to the framework. You didn't manually change those snippets in the generated class. You also don't need to publish what you built on top of the framework.

So in my opinion you don't need to make the source available as long as you didn't modify the library itself. Then you need to publish those changes. 

I think [question 15](https://eclipse.org/legal/eplfaq.php#COMPILEWOMOD) answers that. Note that EPL has another requirement, you need to mention that you make use of this library.

**Comment by 2xbass** [comment]
@vRallev, if the generated code contains snippets that are licensed under the EPL then the generated code is arguably a derivative work of the snippets and therefore those changes also need to be made available under the EPL. This is a very specific case and not any other case such as making changes to the framework.

Is it your intention that the generated code would be subject to licensing terms?

FYI the problem of an open source-licensed code generator creating output that includes bits of open source-licensed code is not a new one and it's why some tools (e.g. Doxygen, Bison, etc.) address this specifically in their licensing. There's an interesting paper that describes this here: https://arxiv.org/pdf/1412.2963.pdf.

**Comment by vRallev** [comment]
That's interesting. Thanks for the links.

No, I don't intend that the generated code is subject to licensing terms. What would be the easiest way to resolve this? Do you have a recommendation?

**Comment by eapache** [comment]
I would think that something like the doxygen sentence would be sufficient. I'm not sure if it would go better on the main page or directly in the license file. I'm also not sure how things are affected by this project being derived from icepick. Perhaps @frankiesardo would care to way in?

**Comment by vRallev** [comment]
This would probably be fine as the processor was completely rewritten in Java and has nothing in common with the processor in Icepick. The generated code is also not the same and no code pieces of the generated code were reused. Only the library code is forked from Icepick. 

I'll create a PR tomorrow.

**Comment by 2xbass** [comment]
@vRallev, the ideal thing would be that you add a Doxygen-style in the license file such as: "Documents produced by android-state are deemed to be derivative works derived from the input used in their production and are deemed not to be derivative works of android-state; they are not affected by this license."

**Comment by carlbenson** [comment]
The paper clearly states that it only implies EPL in the generated code if the generator inserts pieces of its own source code into the generated code. Is this the case here?

**Comment by vRallev** [comment]
Probably not. I reached out to our legal team. I'm sorry about the delay.

**Comment by eapache** [comment]
> I reached out to our legal team. I'm sorry about the delay.

Thanks for being thorough, hopefully they agree that a doxygen-style note in the license is sufficient.

**Comment by 2xbass** [comment]
"Pieces of its own source code" could potentially include literal strings embedded in the source code (meaning interspersed in one or more source files). One clean way around this is to ensure such strings are externalized and in a separately licensed file.

**Comment by carlbenson** [comment]
[StateProcessor.java#293](https://github.com/evernote/android-state/blob/master/processor/src/main/java/com/evernote/android/state/StateProcessor.java#L293) is just one example of injecting pieces of the source code into the user's code.

**Comment by vRallev** [comment]
Our legal team is working on the issue. What Doxygen did in their project will be probably enough, but I'm waiting for a final confirmation. Software licenses aren't that easy :-) I'll let you know when I get a response.

Thanks again for bringing up that issue.

**Comment by vRallev** [comment]
I'm sorry for the too long delay, but I finally received a response. All generated files will be licensed differently to avoid any confusion. I'll update the library tomorrow and release a new stable version.

**Comment by JEuler** [comment]
Sorry to post in closed issue. But I have question about licence. So, if I'm using this library in my project and then deploy it to Google Play, what I should do? As I understand I should not publish sources. But I need to mention that I'm using this library. Is that correct? If yes, how I should mention it (and where)? In app?
