### ISSUE TITLE
Clarify usage of kapt in build.gradle

### ISSUE THREAD

**Issue by efung** [evernote/android-state#14]
In the README.md, it says this is needed in your `build.gradle`:

```
dependencies {
    // …
    // Kotlin & Java
    kapt 'com.evernote:android-state-processor:1.0.5'
}
```

If I'm not using Kotlin at all in my project, I wouldn't be including the Kotlin gradle plugin, so wouldn't have `kapt`.

Or does the comment there mean if your app is using a mix of Kotlin and Java?

**Comment by vRallev** [comment]
Well, the README says this:
```groovy
dependencies {
    ...
    // Java only
    annotationProcessor 'com.evernote:android-state-processor:1.0.5'

    // Kotlin & Java
    kapt 'com.evernote:android-state-processor:1.0.5'
}
```

So..
* Java only: `annotationProcessor`
* Kotlin only: `kapt`
* Java and Kotlin mixed: `kapt`

I hope it's clearer now.

**Comment by efung** [comment]
Thanks for the clarification. I don't use Kotlin, so I didn't know what
kapt was for at first.

**Comment by vRallev** [comment]
No prob!
