### ISSUE TITLE
Proguard issues with code obfuscation

### ISSUE THREAD

**Issue by radzio** [evernote/android-state#15]
**android-state** has exactly the same issue with code obfuscation like the icepick lib.

In every project, I'm using android-state class names are not obfuscated even if they can be.

Related issue:
https://github.com/frankiesardo/icepick/issues/97

**Comment by vRallev** [comment]
Can you provide a proguard config that will fail, if the library wouldn't come with its own config? To be honest, I haven't tried it myself, yet. But I definitely would like to improve the situation.

**Comment by radzio** [comment]
@vRallev I'm able to reproduce this error in **android-state** demo project. I've just compiled it with Android Studio 2.3.1. 

IMO it might be connected to Android Studio Proguard version. In Android 2.3 Google [has updated](https://sites.google.com/a/android.com/tools/recent/androidstudio23canary3isnowavailable) Proguard to 5.3.2. Moreover,  in January and February, everything was fine. I have found this issue during a routine check of the generated apks.

Everything works when I comment one line in android-state library proguard file:

```
-dontwarn com.evernote.android.state.**
-keep class com.evernote.android.state.** { *; }
-keep class **$$StateSaver { *; }
-keepclasseswithmembernames class * {
    @com.evernote.android.state.* <fields>;
}
#-keepnames class * { @com.evernote.android.state.State *;} - this line causes problems
```

**Comment by vRallev** [comment]
Okay, thanks! I'll take a look at this this week.

**Comment by vRallev** [comment]
I'm really sorry for the too long delay. But I finally had time to take a look at it. It turned out, that two rules were wrong. I fixed that and published a new snapshot build. I'd appreciate if you could give it a try:
```groovy
repositories {
    jcenter()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile 'com.evernote:android-state:1.0.7-SNAPSHOT'
    kapt 'com.evernote:android-state-processor:1.0.7-SNAPSHOT'
}
```

Note that this will break the reflection code, if you use `@State(reflection = true)`. I'll be working on that next.

**Comment by vRallev** [comment]
I fixed the reflection part today. There's a new annotation `StateReflection` if you rely on reflection. Everything should be working properly now. Feedback is appreciated. Thanks for bringing up this issue!
