### ISSUE TITLE
Support annotating methods @State

### ISSUE THREAD

**Issue by paour** [evernote/android-state#16]
Taking your improvements to Icepick one step further, why not allow annotations on a getter/setter-like method so that state that is not backed up to a variable can be saved.

My use-case is for a media player that should persist the current seek of the track, which is available by asking the `MediaPlayer` instance, but is not usually saved in the fragment or activity state.

**Comment by vRallev** [comment]
That sounds like an useful feature to me.

**Comment by vRallev** [comment]
After thinking about it, it's easier in my opinion to use a backing field. What you are suggesting:
```java
@State
public int getSomething() {
   return something;
}

@State
public void setSomething(int something) {
    this.something = something;
}
```

You could achieve the same with a field and wouldn't need to annotate both methods.
```java
@State
private int something;

public int getSomething() {
    return somethingElse;
}

public void setSomething(int something) {
    this.somethingElse = something;
}
```

**Comment by paour** [comment]
The use-case I had in mind was more along the lines of

```
@State
public boolean getPlaying() {
   return mediaPlayer.isPlaying();
}

@State
public void setPlaying(boolean playing) {
    if (playing) {
        mediaPlayer.start();
    }
}
```

**Comment by vRallev** [comment]
Change that to 
```java
@State
private boolean playing;

public boolean getPlaying() {
   return mediaPlayer.isPlaying();
}

public void setPlaying(boolean playing) {
    if (playing) {
        mediaPlayer.start();
    }
}
```
And it's working.
