### ISSUE TITLE
Saving and restoring state on superclasses

### ISSUE THREAD

**Issue by paour** [evernote/android-state#17]
This may be a product of the rewritten annotation processor, and refers to [this issue](https://github.com/frankiesardo/icepick/issues/9), which was fixed in Icepick.

If I have:

```
class ActivityA extends Activity {
    @State int a;

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        StateSaver.saveInstanceState(this, outState);
    }
}

class ActivityB extends ActivityA {
    @State int b;
}
```

the annotation processor generates code for both activities, but when saving the state of an `ActivityB` instance, only `b` is saved.

Either the annotation processor needs to include the classe's parents' state when generating the `save` and `restore` methods, or `StateSaver.saveInstanceState` needs to walk the class hierarchy at runtime.

**Comment by paour** [comment]
Whoops, please disregard, I missed the super call chain in `save` and `restore` and my code had a bug!

**Comment by paour** [comment]
(the bug was: my fields weren't private, so the get/setters were bypassed)

**Comment by vRallev** [comment]
:)
