### ISSUE TITLE
StateSaver#getInjector return null

### ISSUE THREAD

**Issue by talentprince** [evernote/android-state#20]
Don't know why but the `getInjector` return null, can not find XXXX$$StateSaver generated class, so that all the @State field cannot be saved into system state bundle.

Something related to kapt?

**Comment by vRallev** [comment]
Do you have a reproducible sample? Hard to say what's going wrong.

**Comment by elye** [comment]
Sounds similar to issue https://github.com/evernote/android-state/issues/21

**Comment by vRallev** [comment]
@talentprince Can you test the solution in #21?

**Comment by vRallev** [comment]
Solution is in #21
