### ISSUE TITLE
Feature request: Type Converters

### ISSUE THREAD

**Issue by ragunathjawahar** [evernote/android-state#22]
There are situations where type converters could make saving state and restoration simple while using non-parcelable instances. Let's consider a scenario with a `BehaviorRelay` that emits parcelable `NewsUiState` objects.

- At any point of time, the `BehaviorRelay` holds an instance of `NewsUiState`. 
- To save and restore the `BehaviorRelay`, we should have a field that holds the latest `NewsUiState` value was emitted by the `BehaviorRelay` and annotate it with the `@State` annotation.
- While restoration, in the `onCreate` method, we recreate the behavior relay from the restored `NewsUiState` field.

Instead, we could use type converter to encapsulate the state save and restore logic while using non-parcelable objects. Please look at the following crude API example.

```java
public class NewsActivity extends Activity {

    @State
    @TypeConverter(BehaviorRelayConverter.class)   // <-- Type converter annotation
    public BehaviorRelay<NewsUiState> uiStateRelay;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        StateSaver.restoreInstanceState(this, savedInstanceState);
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        StateSaver.saveInstanceState(this, outState);
    }
}
```

```java
public class BehaviorRelayConverter {

    public Parcelable toParcelable(BehaviorRelay<NewsUiState> relay) {
        return relay.getValue();
    }

    public BehaviroRelay<NewsUiState> toRelay(Parcelable parcelable) {
        return BehaviorRelay.create((NewsUiState) parcelable);
    }

}
```

**Comment by vRallev** [comment]
I agree, that sounds good.

**Comment by vRallev** [comment]
Sorry for the late response. I didn't read your feature request careful enough. What you want to achieve is already possible with a custom `Bundler`. 

```java
public class BehaviorRelayBundler implements Bundler<BehaviorRelay<Parcelable>> {
    @Override
    public void put(@NonNull String key, @NonNull BehaviorRelay<Parcelable> relay, @NonNull Bundle bundle) {
        bundle.putParcelable(key, relay.getValue());
    }

    @Nullable
    @Override
    public BehaviorRelay<Parcelable> get(@NonNull String key, @NonNull Bundle bundle) {
        Parcelable parcelable = bundle.getParcelable(key);
        return BehaviorRelay.createDefault(parcelable);
    }
}
```

And then you can use it this way
```java
    @State(BehaviorRelayBundler.class)
    public BehaviorRelay<Parcelable> mRelay;
```

**Comment by ragunathjawahar** [comment]
@vRallev You're right. Closing this issue.
