### ISSUE TITLE
What is the correct proguard?

### ISSUE THREAD

**Issue by talentprince** [evernote/android-state#23]
Hi, team, when my project is using StateSaver in Activity/Fragment, it's fine, because default proguard will keep the name for system views.
but when I use for custom file, it can not find injector because of obfuscate.

I check the README, it shows `This library comes with a ProGuard config. No further steps are required, but all necessary rules can be found here.`

I checked the sample, it's

```
-dontwarn com.evernote.android.state.**
-keep class com.evernote.android.state.** { *; }
-keep class **$$StateSaver { *; }
-keepclassmembers class * {
    @com.evernote.android.state.StateReflection <fields>;
}
```

it will keep the generate class, but it won't keep the class with @State annotation, I don't know what is StateReflection.

then I change it to 

```
-dontwarn com.evernote.android.state.**
-keep class com.evernote.android.state.** { *; }
-keep class **$$StateSaver { *; }
-keepclasseswithmembernames class * {
    @com.evernote.android.state.* <fields>;
 }
-keepnames class * { @com.evernote.android.state.State *;}
```

it works.

**Comment by talentprince** [comment]
My field is default not private, so no need to use @StateReflection (just saw it from README).
Shouldn't we keep all the class with @State annotation like icepick?

**Comment by vRallev** [comment]
Yes, the rule `-keepnames class * { @com.evernote.android.state.State *;}` seems to be necessary. Good catch!

The downside is that this rule also preserves the variable names, although they could be obfuscated. But I didn't find a proguard rule that only keeps the class name and not variable names although they're matching.

**Comment by vRallev** [comment]
Okay, I have a fix ready. Can you give the following build a try?
```groovy
repositories {
    jcenter()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile 'com.evernote:android-state:1.1.1-SNAPSHOT'
    kapt 'com.evernote:android-state-processor:1.1.1-SNAPSHOT'
}
```

**Comment by talentprince** [comment]
Fixed! thanks, after you release, I will change to 1.1.1, now I am still using my proguard

**Comment by vRallev** [comment]
Released: https://github.com/evernote/android-state/releases/tag/v1.1.1
