### ISSUE TITLE
Kotlin: saving ObservableField state error

### ISSUE THREAD

**Issue by kancic** [evernote/android-state#24]
Hi,

in Kotlin I have a field like this:

```Kotlin
@State var email: ObservableField<String> = ObservableField()
```

When I try to compile the code I get an error like this:

```Kotlin
Error:(57, 51) error: incompatible types: String cannot be converted to ObservableField<String>
```

And the affected generated code looks like this:

```Java
@Override
@SuppressWarnings("unchecked")
public void restore(T target, Bundle state) {
    target.setEmail(HELPER.<String>getSerializable(state, "Email"));
}
```

**Comment by vRallev** [comment]
Yes, this looks wrong. Can you provide a really small sample to reproduce the issue for me locally? The `ObservableField` class should be enough.

**Comment by kancic** [comment]
Here it is https://github.com/kancic/State-Error-Reproduction.git

Thank you for the quick reply :)

**Comment by vRallev** [comment]
Thanks, I can reproduce the issue now myself. I'll take a look. For now a custom bundler should do the job for you.

**Comment by kancic** [comment]
Thank you very much.

**Comment by vRallev** [comment]
Okay, I have a fix ready. Can you give the following build a try?
```groovy
repositories {
    jcenter()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile 'com.evernote:android-state:1.1.1-SNAPSHOT'
    kapt 'com.evernote:android-state-processor:1.1.1-SNAPSHOT'
}
```

**Comment by kancic** [comment]
It is working fine now with the updated library, thank you very much. :)

**Comment by vRallev** [comment]
Released: https://github.com/evernote/android-state/releases/tag/v1.1.1
