### ISSUE TITLE
Parcelable List fails to be put into bundle

### ISSUE THREAD

**Issue by colinrtwhite** [evernote/android-state#25]
Using the @State annotation with any `List<T extends Parcelable>` type causes the compilation error "Don't know how to put `java.util.List<T>` into a bundle". I've attached a test project that replicates the issue. Looks like BundlerListParcelable.java is supposed to handle this case.

[TestEvernoteState.zip](https://github.com/evernote/android-state/files/1136668/TestEvernoteState.zip)

**Comment by vRallev** [comment]
As you've pointed out, you need to use `BundlerListParcelable`. 
```
@State List<Test> tests; // your sample, that wrong

// both work, prefer the 2nd, because this doesn't create an extra ArrayList
@State(BundlerListParcelable.class) List<Test> tests1;
@State ArrayList<Test> tests2;
```

**Comment by colinrtwhite** [comment]
Ah sorry, for some reason I thought it was automatically applied. However, it looks like I get the same compiler error while using Kotlin.
[TestEvernoteState.zip](https://github.com/evernote/android-state/files/1137803/TestEvernoteState.zip)

**Comment by vRallev** [comment]
Thanks for the sample. I was able to reproduce the issue.

**Comment by vRallev** [comment]
I've published a new version containing the fix https://github.com/evernote/android-state/releases/tag/v1.1.2 

Feel free to reopen or to create new issue if you find more problems.
