### ISSUE TITLE
Field must be either non-private or provide a getter and setter method

### ISSUE THREAD

**Issue by masmil1988** [evernote/android-state#26]
In my Kotlin project I have only three fragments using Android-State. Each of them has three properties to save and restore. Some of them are like this

`@State lateinit var mVariable: SomethingParcelable`

The others are Strings and Booleans (all variables are called _mSomething_). None of them is private.
Nevertheless I obtain this error:

```
Error:Field must be either non-private or provide a getter and setter method
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I can't say which of my variables is causing this issue, but it seems to be a bug.

**Comment by vRallev** [comment]
Can you provide a sample for me to reproduce the issue?

**Comment by masmil1988** [comment]
These are my variables:
```
@State var mLoadItems: Boolean = false
@State var mNextPageToken: String? = null
@State var mStartingItem: Item?
```
where _Item_ is a Parcelable data class.

I save the state in onSaveInstanceState
```
override fun onSaveInstanceState(outState: Bundle) {
    super.onSaveInstanceState(outState)
    StateSaver.saveInstanceState(this, outState);
}
```

and restore it in onActivityCreated
```
override fun onActivityCreated(savedInstanceState: Bundle?) {
    super.onActivityCreated(savedInstanceState)
    StateSaver.restoreInstanceState(this, savedInstanceState);
    // my other stuff
}
```

This is all. I suspect it is a bug (I've read about <a href="https://github.com/evernote/android-state/issues/18">this other issue</a>, maybe related), or maybe Dugger2 is doing something (it is terrible to debug when there is dugger)...

**Comment by vRallev** [comment]
I found the issue. There were some problems with the Hungarian notation in Kotlin. The snippets helped a lot. That's fixed in version `1.1.3`. Please give it a try.

https://github.com/evernote/android-state/releases/tag/v1.1.3

**Comment by thelong1EU** [comment]
I have the same problem here:
Error:Field currentTalk must be either non-private or provide a getter and setter method

**Comment by vRallev** [comment]
@thelong1EU Even with the new version?

**Comment by thelong1EU** [comment]
Yes. When I removed the internal modifier, it was all good.

**Comment by vRallev** [comment]
Just to be 100% sure, can you add a snippet? Then I'll take a look at this in the next version.

**Comment by iukky** [comment]
same problem here

**Comment by GrahamBorland** [comment]
Same here.
```kotlin
@State internal var analyticsUsedShortcut = false
```
```
Error:Field analyticsUsedShortcut must be either non-private or provide a getter and setter method
```
Removing the `internal` fixes it.

**Comment by vRallev** [comment]
@GrahamBorland Can you test `1.2.0` which I released just a couple of minutes ago? If it's still reproducible, could you maybe share a snippet or even contribute a failing pull request?

**Comment by GrahamBorland** [comment]
@vRallev Still happens with 1.2.0. I'll try to isolate a repro case.
