### ISSUE TITLE
State save not working

### ISSUE THREAD

**Issue by ch8154** [evernote/android-state#28]
Hi, I use this lib to save an Int var with Kotlin in my activity. but not working. How do I use this library correctly?

`
 class MainActivity : BaseActivity(), MainMvpView {

    @State var currentPosition: Int = 0

        if (savedInstanceState == null) {

           //do something...

        } else {

            StateSaver.restoreInstanceState(this, savedInstanceState)
           //do something after restore.

        }

    override fun onSaveInstanceState(outState: Bundle?) {

        super.onSaveInstanceState(outState)

        if (outState != null) {

            StateSaver.saveInstanceState(this, outState) // outState is nothing now.

        }
    }
 }
`
Looks like not save successful,because outState don't contains currentPosition when I use breakpoint to see that. 

Forgive my poor English and please help me. Thanks!

**Comment by Eranot** [comment]
Check if this line is being called:
`StateSaver.saveInstanceState(this, outState) // outState is nothing now.
`
My guess is that this if "if (outState != null)" is never true, cause outstate is null until you put something there. So, you are never even saving the variable.
Try take out the if statement, transform this:

```
if (outState != null) {
        StateSaver.saveInstanceState(this, outState) // outState is nothing now.
}
```

to just this:
`StateSaver.saveInstanceState(this, outState) // outState is nothing now.`

**Comment by vRallev** [comment]
Please provide a sample to reproduce the issue. That code snippet isn't enough.

**Comment by ch8154** [comment]
I tried this again and I found the problem gone, and I can't reproduce the problem. So I thought maybe my last code had some problems. 

Thank you for your help and reply !
