### ISSUE TITLE
Error restoring a List

### ISSUE THREAD

**Issue by Eranot** [evernote/android-state#29]
Hey, nice work with the project.
I have encoutered this error:

Error:(60, 59) error: incompatible types: Attribute cannot be converted to ArrayList<Attribute>

The error is refering to this attribute:
`@State var attributes = arrayListOf<Attribute>()`

On my onCreateView Im calling:
`StateSaver.restoreInstanceState(this, savedInstanceState)`

On onSaveInstanceState Im calling:
`StateSaver.saveInstanceState(this, outState!!)`

I guess the problem is in the generated class, cause when the error comes, this file pops up:
```
package com.example.android.tabsandnavs.Fragments;

import android.os.Bundle;
import com.evernote.android.state.Bundler;
import com.evernote.android.state.InjectionHelper;
import com.evernote.android.state.Injector;
import com.example.android.tabsandnavs.Entities.Attribute;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;

public class CreateSheetFragment$$StateSaver<T extends CreateSheetFragment> extends Injector.Object<T> {
  private static final HashMap<String, Bundler<?>> BUNDLERS = new HashMap<String, Bundler<?>>();

  private static final InjectionHelper HELPER = new InjectionHelper("com.example.android.tabsandnavs.Fragments.CreateSheetFragment$$StateSaver", BUNDLERS);

  static {
  }

  @Override
  @SuppressWarnings("unchecked")
  public void save(T target, Bundle state) {
    HELPER.putString(state, "SheetName", target.getSheetName());
    HELPER.putSerializable(state, "Attributes", target.getAttributes());
  }

  @Override
  @SuppressWarnings("unchecked")
  public void restore(T target, Bundle state) {
    target.setSheetName(HELPER.getString(state, "SheetName"));
    //ERROR HERE \/ ============================================
    target.setAttributes(HELPER.<Attribute>getSerializable(state, "Attributes")); // <------ ERROR HERE
  }
}
```
Give special attention to this line:

`target.setAttributes(HELPER.<Attribute>getSerializable(state, "Attributes"));`
The converting is wrong.

Other informations:
The class Attribute extends SugarRecord from SugarORM
The class also implements Serializable
Im using Kotlin

Thanks.

**Comment by vRallev** [comment]
Can you provide a sample for me to reproduce the issue? There are many tests in this project, maybe you can add one there as well.

**Comment by Eranot** [comment]
Here it goes
https://github.com/Eranot/Android-State-Error-With-SugarORM
I found a solution creating a simple Bundler, but if you still want to see what its going on. The solution is in the project too.

**Comment by vRallev** [comment]
Thanks, I can reproduce the issue! I'll take a look next week (I'm still on vacation this week).

**Comment by Eranot** [comment]
That's fine, I'm glad I could help the library to improve, and again, awesome work, congratz

**Comment by vRallev** [comment]
Fixed in the new version: https://github.com/evernote/android-state/releases/tag/v1.1.4
