### ISSUE TITLE
Bug with Serializable field in Kotlin class

### ISSUE THREAD

**Issue by deviant-studio** [evernote/android-state#3]
Hi, guys!
Great lib! I think there is no support for serializable (parcelable?) kotlin properties.
Here is my class
```
class User : Serializable
```
and here is how i use it in Activity
```
@com.evernote.android.state.State
var user: User = User()
```

Android Studio complains on this autogenerated line:
```
target.setUser(HELPER.getSerializable(state, "User"));
```

**Comment by vRallev** [comment]
Hey, thanks for reporting. I noticed this myself yesterday and it's fixed in version `1.0.1`. Can you give it a try?

**Comment by deviant-studio** [comment]
that was amazingly fast! thanks, it works :)

**Comment by vRallev** [comment]
Nice!
