### ISSUE TITLE
 java.lang.ClassCastException when safeGet

### ISSUE THREAD

**Issue by talentprince** [evernote/android-state#30]
Hi team,

We met a new issue and can not reproduce locally, any thoughts?

```
Caused by java.lang.ClassCastException
--
  | com.evernote.android.state.StateSaver.getInjector (SourceFile:47)
  | com.evernote.android.state.StateSaver.safeGet (SourceFile:59)
  | com.evernote.android.state.StateSaver.saveInstanceState (SourceFile:76)
```

**Comment by vRallev** [comment]
I don't know what's wrong. In this line it tries to load the generated classes. Without a reproducible sample I can't do anything.

**Comment by vRallev** [comment]
Fixed in the new version: https://github.com/evernote/android-state/releases/tag/v1.1.4
