### ISSUE TITLE
How to Save ObservableArrayList ?

### ISSUE THREAD

**Issue by KoutaMatsushita** [evernote/android-state#38]
Hello.
My Android project is using Databinding.
I want to save this Object.

```kotlin
data class Todo(val id: Long: val title: String): Serializable

@State
var todoList = ObservableArrayList<Todo>()
```

But, a compile error occurred.

```
error: incompatible types: Todo cannot be converted to ObservableArrayList<Todo>
```

This is generated code:
```java
@Override
@SuppressWarnings("unchecked")
public void restore(T target, Bundle state) {
  target.setTodoList(HELPER.<Todo>getSerializable(state, "TodoList"));
}
```

What should I do?

**Comment by vRallev** [comment]
Which version are you using? Can you provide a sample?

**Comment by KoutaMatsushita** [comment]
@vRallev 
I used version `1.1.6`

Here is this sample:
https://github.com/KoutaMatsushita/Android-State-Sample.git

thank you quick reply 😄

**Comment by vRallev** [comment]
Can you please try again with version `1.2.1`? Please reopen if it's still an issue, thanks.
