### ISSUE TITLE
Lint complains about usage of old API

### ISSUE THREAD

**Issue by DreierF** [evernote/android-state#39]
Seems like the bundles lint checks will be disabled in the near future because they use an old API.
![image](https://user-images.githubusercontent.com/5631865/34419104-46e1490c-ec02-11e7-992a-47e3c2996507.png)

Just wanted to make sure you are aware of the issue.

I'm using Android Plugin 3.0.1 on Gradle 4.1.

**Comment by vRallev** [comment]
Thanks for opening the issue. We're aware of it.

CC @junchengc

**Comment by vRallev** [comment]
I just released version `1.2.0`. The issue should be fixed now.
