### ISSUE TITLE
Proguard config breaks obfuscation of class names

### ISSUE THREAD

**Issue by bobrusha** [evernote/android-state#43]
Current progurad config prevents obfuscation of **all** class names in project.
This issue was fixed https://github.com/evernote/android-state/commit/a367d8d387ea89eacc51fee2ff273e8c9ac17517#diff-f2642babefcefdbfdda3582fb7885354
But after that changes were reverted https://github.com/evernote/android-state/commit/34ee48f488646023cbc3b47bb06e85f36922fe89#diff-f2642babefcefdbfdda3582fb7885354

**Comment by vganin** [comment]
It seems that there is an error in 34ee48f: `-keepnames` preserves class names and its members while you were needing `-keepclasseswithmembernames` which implements desired conditional logic to preserve class name and member names **if** member wildcards are met.

**Comment by vRallev** [comment]
This should have been fixed in `1.2.1`. Please give this version a try and let me know if you still run into issues. Thanks for reporting.

**Comment by KR1sis** [comment]
It looks like that this fix is wrong. 
With current proguard rules the classes containing @State annotation are obfuscated and change their names. State can't be restored, because in InjectorHelper uses an original class name for baseKey and it doesn't preserved.

**Comment by KR1sis** [comment]
If add 
-keepclasseswithmembernames class * { @com.evernote.android.state.State <fields>;}
it works correctly.
But
-keepclasseswithmembernames class * { @com.evernote.android.state.State *;}
doesn't work

**Comment by vRallev** [comment]
@KR1sis I can reproduce the issue now. My tests had a wrong config. Thanks for the hint!

**Comment by vRallev** [comment]
@KR1sis I've updated the config in 1.3.1 https://github.com/evernote/android-state/releases/tag/v1.3.1
