### ISSUE TITLE
Deal with private fields via Bytecode [ENHANCEMENT]

### ISSUE THREAD

**Issue by AlexShafir** [evernote/android-state#45]
I hope this can be achieved in remote future.

Whenever we encounter field marked as private, instead of reflection:

1. Private modifiers are removed in bytecode.

2. For this field regular state class is generated (as though it is non-private), but instead 
    of saving via annotation processor it is compiled to bytecode and then saved.
    For user reference it can be saved as annotation processor does, but with `.txt` file format. 

This approach combines flexibility of Reflection and speed of ordinary code.

It can be done via Android Gradle Transform API ([1](http://tools.android.com/tech-docs/new-build-system/transform-api), [2](https://afterecho.uk/blog/create-a-standalone-gradle-plugin-for-android-part-4-the-transform-api.html)) as a hook for `.class` files.

**Comment by vRallev** [comment]
This sounds like an interesting enhancement. Feel free to create a PR. I don't have the time in the near future to implement this.

**Comment by vRallev** [comment]
I'm closing this issue since I won't be able to implement this.
