### ISSUE TITLE
Bundler that modifies object in get method

### ISSUE THREAD

**Issue by AlexShafir** [evernote/android-state#47]
**Problem**
Some objects whose state should be saved are constructed by other library.
For instance, `GoogleMap`.
Thus `Bundler`'s get method's return value is not applicable here.

**Proposal** 
Alternative `Bundler` that receives object to restore state of in get method and returns nothing.

**Proposal example**

```java
class MyMap extends MapFragment implements OnMapReadyCallback {

   @State(MapBundler.class) GoogleMap map;

   Bundle savedInstanceState;

   void onViewCreated(Bundle savedInstanceState) {
      this.savedInstanceState = savedInstanceState;
      getMapAsync(this);
   }

   void onMapReady(GoogleMap map) {
      this.map = map;
      StateSaver.restoreInstanceState(map, this.savedInstanceState);
   }

   void onSaveInstanceState(Bundle outState) {
      StateSaver.saveInstanceState(this.map, outState);
      super.onSaveInstanceState(outState);
   }

}


class MapBundler implements MutatingBundler<GoogleMap> {
   void put(String key, GoogleMap map, Bundle bundle) {
      bundle.putFloat(key + "zoom", map.getCameraPosition().zoom);
   }

   // <<<<<<<<<<<<<<<<<<< Here is the difference >>>>>>>>>>>>>>>>>>>
   // GoogleMap get(String key, Bundler bundle) {...} <--------- This is previous state
   void get(String key, @NonNull GoogleMap map, Bundle bundle) {
      float zoomLevel = bundle.getFloat(key + "zoom");
      map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(0, 0), zoomLevel));
   }
```

**Comment by vRallev** [comment]
I'm not sure if I can follow you. Do you want something that is lazily retrieved?

**Comment by AlexShafir** [comment]
See my updated issue above.

Not sure if it can be called "lazy". Probably "mutable", "mutating"

**Comment by vRallev** [comment]
Sorry, but the sample is confusing to me. What prevents you from doing this now already? You have full control over when you save or restore the instance state.

**Comment by AlexShafir** [comment]
Yes, you are right, it was confusing a bit. I changed title to **Proposal Example**

Currently `Bundler` returns value in `get `method.
For objects like `GoogleMap` it is not suitable however.
You can only modify their state and not create them.

No, current `Bundler` does not allow modifying existing object, it only replaces value of field.

**Comment by vRallev** [comment]
I don't get your point and what you're trying isn't recommended anyways. You should only store lightweight objects in the instance state and not full objects. You have full control over when you want to store and restore objects, so you already have all the power. 

An easier solution for you would be to create a separate variable for the zoom level and save this value.

**Comment by AlexShafir** [comment]
"You should only store lightweight objects in the instance state and not full objects."

- I do not try to save whole GoogleMap. Only its properties.

"An easier solution for you would be to create a separate variable for the zoom level and save this value."

- But I do not want to pollute outer class! I don't need zoom level, camera coords etc. during runtime

"I don't get your point and what you're trying isn't recommended anyways."

- It breaks immutability?
