### ISSUE TITLE
Support incremental annotation processing

### ISSUE THREAD

**Issue by tprochazka** [evernote/android-state#48]
Gradle 4.7 provides support for incremental annotation processing.
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

It would be nice to see this lib supporting it. The change is not that big.

**Comment by tprochazka** [comment]
It is already discussed and implemented here
https://github.com/JakeWharton/butterknife/pull/1230

**Comment by vRallev** [comment]
Yes, I'll definitely add support for it. Thanks for linking butterknife.

**Comment by tprochazka** [comment]
Gradle 4.7 is already out.

**Comment by vRallev** [comment]
It isn't very high on my list right now. Incremental annotation processing will only work, if all annotation processors do support it, e.g. Dagger and Room don't support it, yet. If you use Kotlin with Kapt, then it also won't work. I'm not saying it isn't a good approach, I only mean that multiple things need to come together to have a benefit.

**Comment by oehme** [comment]
If everyone takes that stance it won't happen at all ;) It's really easy to support it for most processors, so I encourage you to reconsider. The Kotlin team is already in contact with us and I'm sure it'll work soon for Kapt.

**Comment by vRallev** [comment]
I'm with you. Right now it's low on the TODO list for us, because Kapt isn't supported, yet, and we use Kapt :-) I definitely want to support the incremental processing, because that's the slowest part in our builds.

**Comment by vRallev** [comment]
@oehme and @tprochazka I've created #49, it would be helpful if you could take a look at it. Compiling with `--info` looks good.

**Comment by tprochazka** [comment]
I just look on it. But @oehme is the true expert here.
But I can try to build it and use locally.
Just small question, you update to grade 4.8 RC2, it is not working with 4.7 properly?

**Comment by tprochazka** [comment]
For such testing is extremely useful when project support "./gradlew install" to install artifact without any configuration to local maven repository. There is not set up "group" and from same reason library module is skiped. For example in butternife gradlew install works correctly.

 But I managed it and it looks that it works. I was just not able to make it working WIth Gradle 4.7 for some reason, it detect the state of annotation processors like UNKNOWN, but with 4.8 rc2 yes. I will investigate it more.

Thanks a lot!

**Comment by vRallev** [comment]
I'm still using the old Maven plugin where you need to run `./gradlew uploadArchives`. This will install the artifact to your local maven repository.

**Comment by tprochazka** [comment]
Ah. I completely forgot that this was used before :-(  So I wasted some time by fixing project to be able use install :-( My fault.

**Comment by vRallev** [comment]
Incremental annotation processing is now supported in version `1.3.0` https://github.com/evernote/android-state/releases/tag/v1.3.0

**Comment by oehme** [comment]
A much better solution is using `--include-build` instead of installing to mavenLocal.
