### ISSUE TITLE
error during building gradle

### ISSUE THREAD

**Issue by gugakatsi** [evernote/android-state#5]
```
Error:Execution failed for task ':app:transformJackWithJackForDebug'.
> java.util.ServiceConfigurationError: javax.annotation.processing.Processor: Provider com.evernote.android.state.StateProcessor could not be instantiated
```
that's all i get when i try to build gradle , thanks in advance.

**Comment by vRallev** [comment]
Hi, I cannot reproduce this issue. Can you provide more information? Or better a simple demo project that reproduces the issue?

However, I ran into other issues with Jack. In the meantime I would recommend disabled Jack and to use RetroLambda instead.

**Comment by gugakatsi** [comment]
@vRallev i'll do it tomorrow morning , no problem.

**Comment by vRallev** [comment]
@gugakatsi I released the new version `1.0.3`, which adds a specific fix for the Jack compiler. Please give this new version a try and let me know if it works for you or not.

**Comment by gugakatsi** [comment]
@vRallev worked fine now, thanks again, sry that i could posted info that i promised , did't really have time since than.

**Comment by vRallev** [comment]
No worries, can the ticket be closed?

**Comment by gugakatsi** [comment]
@vRallev yes of course.
