### ISSUE TITLE
ParcelableArray is restored and stored as Serializable

### ISSUE THREAD

**Issue by shaishavgandhi05** [evernote/android-state#53]
It looks like when you apply `@State` to an array of objects that implement Parcelable, it is saved and restored as Serializable.

**Comment by vRallev** [comment]
I can reproduce the issue. Thanks for reporting!

**Comment by shaishavgandhi05** [comment]
Happy to send a PR if you want!

**Comment by vRallev** [comment]
Thanks, but I have a fix almost ready. I appreciate the help, though!

**Comment by vRallev** [comment]
That should be fixed in `1.3.1`. Please let me know if it works for you. https://github.com/evernote/android-state/releases/tag/v1.3.1
