### ISSUE TITLE
java.lang.Object conflicts with com.evernote.android.state.Injector.Object which results compilation error

### ISSUE THREAD

**Issue by RahmanAshiq** [evernote/android-state#55]
Using version: 1.3.1
Getting compilation error "Error:(61, 90) error: incompatible types: ArrayList<KeyValuePair<String,com.evernote.android.state.Injector.Object>> cannot be converted to ArrayList<KeyValuePair<String,java.lang.Object>>" with the following class implementation.

    public class KeyValuePair <K, V> {
    private K key;
    private V value;

    public KeyValuePair(K key, V value) {
        this.key = key;
        this.value = value;
    }

    public K getKey() {
        return key;
    }

    public void setKey(K key) {
        this.key = key;
    }

    public V getValue() {
        return value;
    }

    public void setValue(V value) {
        this.value = value;
    }
    public static final class ListKeyValuePairBundlerStringObjectAsString implements Bundler<ArrayList<KeyValuePair<String, java.lang.Object>>> {
        @Override
        public void put(@NonNull String key, @NonNull ArrayList<KeyValuePair<String, java.lang.Object>> list, @NonNull Bundle bundle) {
            if(list != null) {
                bundle.putInt(key + "size", list.size());
                for (int i = 0; i < list.size(); i++) {
                    KeyValuePair<String, java.lang.Object> pair = list.get(i);
                    bundle.putString(key + "key" + i, pair.key);
                    bundle.putString(key + "value" + i, pair.value instanceof String ? (String) pair.value : "");
                }
            } else {
                bundle.putString(key+"null", "");
            }
        }

        @Nullable
        @Override
        public ArrayList<KeyValuePair<String, java.lang.Object>> get(@NonNull String key, @NonNull Bundle bundle) {
            if (bundle.containsKey(key+"null")) {
                return null;
            } else {
                ArrayList<KeyValuePair<String, java.lang.Object>> list = new ArrayList<KeyValuePair<String, java.lang.Object>>();
                int size = bundle.getInt(key + "size", 0);
                for(int i = 0; i < size; i++) {
                    list.add(new KeyValuePair<String, java.lang.Object>(bundle.getString(key + "key" + i, ""), bundle.getString(key + "value" + i, "")));
                }
                return list;
            }
        }
    }
    }

Error show's in the following function
    `public void restore(T target, Bundle state) {
    target.setGeneralItems(HELPER.<ArrayList<KeyValuePair<String, Object>>>getWithBundler(state, "GeneralItems"));
      }`

In fragment 
`@State(KeyValuePair.ListKeyValuePairBundlerStringObjectAsString.class)
    private ArrayList<KeyValuePair<String, java.lang.Object>> generalItems;`

**Comment by vRallev** [comment]
I'm sorry for the long delay. Please provide a full sample app, if this is still an issue. Then I'm going to reopen this issue.

**Comment by RahmanAshiq** [comment]
Clarification needed. What do you mean by full sample app? Some github repo link or the Activity class where this is used? As which class I have given here was actually from my project.....

**Comment by vRallev** [comment]
I mean a Github project that I can checkout and build without making any changes.
