### ISSUE TITLE
Can't get android-state to work

### ISSUE THREAD

**Issue by menjoo** [evernote/android-state#60]
Hi i'm trying to get the library to work without any luck even in a "file->new project" situation. 
I can't figure out what is different between the demo app in this repo and mine.

I've put it on https://github.com/menjoo/StateSaverDemo

All i did:
* Create new project
* Add dependency to version 1.3.1 (because new project is not Android X yet)
* Add App class to manifest with the `setEnabledForAllActivitiesAndSupportFragments` line
* Copied simple activity test code from your demo app
* When running the app with "don't keep activities" active or just rotate the screen, the logs keeps showing `onResume mTest1=1 test2=1` indicating state is not saved.

Is there anything special i am missing here?

**Comment by vRallev** [comment]
You forgot to apply the Kapt plugin in your gradle files. After this it'll work.
```
apply plugin: 'kotlin-kapt'
```
