### ISSUE TITLE
Gradle build failed More than one file was found with OS independent path 'META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version

### ISSUE THREAD

**Issue by sharmapraveen91** [evernote/android-state#62]
after integrating it. Unable to gradle-build

Getting below error 
`More than one file was found with OS independent path 'META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version'`

**Comment by vRallev** [comment]
That's not an issue of the library, see https://stackoverflow.com/questions/37283892/how-to-exclude-all-files-under-a-directory-in-gradle

**Comment by wangle82** [comment]
More than one file was found with OS independent path 'schemaorg_apache_xmlbeans/system/sE130CAA0A01A7CDE5A2B4FEB8B311707/cttxbxcontent1133type.xsb'

**Comment by wangle82** [comment]
上面的问题，怎么处理啊？
