### ISSUE TITLE
State saver library doesn't seem to work on Kotlin 1.0.6

### ISSUE THREAD

**Issue by tudorgk** [evernote/android-state#7]
Hello guys!

I am trying to find a good library for handling instance saving/restoring and ended up here with the promise that it will work with Kotlin. I don't know about other versions, but it seems that for 1.0.6 it doesn't work.

I have pasted here a link to a demo project that  confirms the issue. You can find the repo [here](https://github.com/tudorgk/StateSaverKotlin).

Best of luck,
Tudor

**Comment by vRallev** [comment]
Hey,

I found the issue in your sample. Change
```groovy
annotationProcessor 'com.evernote:android-state-processor:1.0.3'
```
to
```groovy
kapt 'com.evernote:android-state-processor:1.0.3'
```

Kotlin has its own annotation processor. After that it should work. 

I'm sorry about the trouble, I forgot to mention this in the documentation.

**Comment by tudorgk** [comment]
Great! 

Keep up the good work!
